/* generated by embed/build-allowlist.js — do not edit */
(function () {
  'use strict';
  var _b = ["bG9jYWxob3N0OjgwMDA=","MTI3LjAuMC4xOjgwMDA=","aXN0cnVjdGUub3Jn","d3d3LmlzdHJ1Y3RlLm9yZw=="];
  var _d = Object.freeze(_b.map(function (s) { return atob(s); }));
  Object.defineProperty(window, '__EQN_ALLOWED_DOMAINS__', {
    value: _d,
    writable: false,
    configurable: false,
    enumerable: false,
  });
})();
